// 総武線沿線（千葉〜市川）の施設データ
const tsudanumaData = {
    // 中心座標（総武線沿線の中央付近）
    center: {
        lat: 35.6800,
        lng: 140.0000,
        zoom: 12
    },

    // 施設データ
    facilities: [
        // 駅・交通
        {
            id: 1,
            name: "津田沼駅（JR総武線）",
            category: "station",
            lat: 35.6916,
            lng: 140.0211,
            description: "JR総武線の駅。快速停車駅で、東京都心へのアクセスが便利です。",
            icon: "🚉",
            address: "千葉県習志野市津田沼1丁目",
            hours: "始発〜終電",
            phone: "047-472-0171",
            website: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=1382",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 0
        },
        {
            id: 2,
            name: "新津田沼駅（新京成線）",
            category: "station",
            lat: 35.6891,
            lng: 140.0242,
            description: "新京成線の駅。津田沼駅から徒歩圏内です。",
            icon: "🚊",
            address: "千葉県習志野市津田沼1丁目10-30",
            hours: "始発〜終電",
            phone: "047-472-1169",
            website: "https://www.shinkeisei.co.jp/railway/station/shin-tsudanuma/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 3
        },

        // ショッピング
        {
            id: 3,
            name: "イオンモール津田沼",
            category: "shopping",
            lat: 35.6851,
            lng: 140.0267,
            description: "大型ショッピングモール。多数の専門店、レストラン、映画館を併設。",
            icon: "🏬",
            address: "千葉県習志野市津田沼1丁目23-1",
            hours: "10:00〜21:00（店舗により異なる）",
            phone: "047-455-1000",
            website: "https://tsudanuma-aeonmall.com/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 5
        },
        {
            id: 4,
            name: "津田沼パルコ（パルコB館）",
            category: "shopping",
            lat: 35.6928,
            lng: 140.0194,
            description: "駅直結のファッションビル。若者向けショップが多数入居。",
            icon: "🛍️",
            address: "千葉県船橋市前原西2-18-1",
            hours: "10:00〜21:00",
            phone: "047-474-1111",
            website: "https://tsudanuma.parco.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 1
        },
        {
            id: 5,
            name: "モリシア津田沼",
            category: "shopping",
            lat: 35.6905,
            lng: 140.0221,
            description: "津田沼駅南口の商業施設。飲食店や雑貨店が充実。",
            icon: "🏢",
            address: "千葉県習志野市谷津1丁目16-1",
            hours: "10:00〜20:00（店舗により異なる）",
            phone: "047-470-1231",
            website: "https://www.moritown-tsudanuma.com/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 2
        },

        // 教育機関
        {
            id: 6,
            name: "千葉工業大学 津田沼キャンパス",
            category: "education",
            lat: 35.6893,
            lng: 140.0354,
            description: "理工系総合大学。先端技術の研究開発を行っています。",
            icon: "🎓",
            address: "千葉県習志野市津田沼2丁目17-1",
            hours: "平日 8:00〜22:00",
            phone: "047-478-0222",
            website: "https://www.it-chiba.ac.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 7
        },
        {
            id: 7,
            name: "日本大学生産工学部",
            category: "education",
            lat: 35.6965,
            lng: 140.0311,
            description: "工学系の学部。実習施設が充実しています。",
            icon: "🏫",
            address: "千葉県習志野市泉町1丁目2-1",
            hours: "平日 8:30〜18:00",
            phone: "047-474-2201",
            website: "https://www.cit.nihon-u.ac.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 10
        },

        // 医療機関
        {
            id: 8,
            name: "谷津保健病院",
            category: "medical",
            lat: 35.6843,
            lng: 140.0189,
            description: "地域の中核病院。救急医療にも対応。",
            icon: "🏥",
            address: "千葉県習志野市谷津4丁目6-16",
            hours: "月〜金 8:30〜17:00／土 8:30〜12:00",
            phone: "047-451-6000",
            website: "https://www.yatsu.or.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 8
        },
        {
            id: 9,
            name: "習志野第一病院",
            category: "medical",
            lat: 35.6938,
            lng: 140.0312,
            description: "総合病院。各種専門外来を設置。",
            icon: "🏥",
            address: "千葉県習志野市津田沼5丁目5-25",
            hours: "月〜土 8:30〜17:00",
            phone: "047-454-1511",
            website: "https://www.narashino-hp.or.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 10
        },

        // 公共施設
        {
            id: 10,
            name: "習志野市役所",
            category: "public",
            lat: 35.6823,
            lng: 140.0265,
            description: "習志野市の行政機関。各種証明書の発行や手続きが可能。",
            icon: "🏛️",
            address: "千葉県習志野市鷺沼2丁目1-1",
            hours: "月〜金 8:30〜17:15",
            phone: "047-451-1151",
            website: "https://www.city.narashino.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 12
        },
        {
            id: 11,
            name: "習志野市立図書館",
            category: "public",
            lat: 35.6948,
            lng: 140.0178,
            description: "公立図書館。蔵書が豊富で学習スペースも完備。",
            icon: "📚",
            address: "千葉県習志野市谷津5丁目16-33",
            hours: "火〜金 9:00〜20:00／土日 9:00〜17:00",
            phone: "047-475-3213",
            website: "https://www.lib.narashino.chiba.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 5
        },
        {
            id: 12,
            name: "習志野文化ホール",
            category: "public",
            lat: 35.6883,
            lng: 140.0158,
            description: "音楽会や演劇公演などが開催される文化施設。",
            icon: "🎭",
            address: "千葉県習志野市谷津1丁目16-1",
            hours: "9:00〜22:00",
            phone: "047-479-1212",
            website: "https://www.narashino-bunka.or.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 6
        },

        // 公園
        {
            id: 13,
            name: "谷津公園",
            category: "park",
            lat: 35.6872,
            lng: 140.0125,
            description: "広大な敷地を持つ公園。バラ園が有名です。",
            icon: "🌳",
            address: "千葉県習志野市谷津3丁目1-14",
            hours: "24時間開放（バラ園: 9:00〜17:00）",
            phone: "047-453-9297",
            website: "https://www.city.narashino.lg.jp/citysales/kanko/kankospot/yatsubaraen.html",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 10
        },
        {
            id: 14,
            name: "谷津干潟",
            category: "park",
            lat: 35.6762,
            lng: 140.0089,
            description: "ラムサール条約登録湿地。野鳥観察の名所。",
            icon: "🦆",
            address: "千葉県習志野市谷津3丁目",
            hours: "24時間開放（自然観察センター: 9:00〜17:00）",
            phone: "047-454-8416",
            website: "https://www.yatsuhigata.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 15
        },
        {
            id: 15,
            name: "袖ケ浦公園",
            category: "park",
            lat: 35.6763,
            lng: 140.0312,
            description: "自然豊かな公園。散策路や池があります。",
            icon: "🌲",
            address: "千葉県習志野市袖ケ浦5丁目4",
            hours: "24時間開放",
            phone: "047-453-9297",
            website: "https://www.city.narashino.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 13
        },

        // その他主要施設
        {
            id: 16,
            name: "ヤマダデンキ LABI津田沼",
            category: "shopping",
            lat: 35.6917,
            lng: 140.0183,
            description: "大型家電量販店。幅広い商品を取り扱い。",
            icon: "🔌",
            address: "千葉県船橋市前原西2-19-1",
            hours: "10:00〜21:00",
            phone: "047-493-1010",
            website: "https://www.yamada-denki.jp/store/contents/?d=3020",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 2
        },
        {
            id: 17,
            name: "京成津田沼駅",
            category: "station",
            lat: 35.6998,
            lng: 140.0214,
            description: "京成本線の駅。成田空港へのアクセスが便利。",
            icon: "🚃",
            address: "千葉県習志野市津田沼5丁目11-1",
            hours: "始発〜終電",
            phone: "047-476-1125",
            website: "https://www.keisei.co.jp/keisei/tetudou/accessj/keisei-tsudanuma.htm",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 8
        },

        // 防災施設（オープンデータ）
        {
            id: 18,
            name: "習志野市立第一中学校（避難所）",
            category: "disaster",
            lat: 35.6885,
            lng: 140.0245,
            description: "指定避難所。災害時の避難場所として利用可能です。",
            icon: "🛡️",
            address: "千葉県習志野市津田沼2丁目3-1",
            hours: "災害時のみ開設",
            phone: "047-451-1151（市役所）",
            website: "https://www.city.narashino.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 5
        },
        {
            id: 19,
            name: "習志野市立津田沼小学校（避難所）",
            category: "disaster",
            lat: 35.6925,
            lng: 140.0265,
            description: "指定避難所。体育館などが避難スペースとなります。",
            icon: "🛡️",
            address: "千葉県習志野市津田沼4丁目5-1",
            hours: "災害時のみ開設",
            phone: "047-451-1151（市役所）",
            website: "https://www.city.narashino.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 8
        },
        {
            id: 20,
            name: "習志野市消防本部",
            category: "disaster",
            lat: 35.6868,
            lng: 140.0298,
            description: "習志野市の消防本部。火災・救急対応を行っています。",
            icon: "🚒",
            address: "千葉県習志野市津田沼5丁目15-1",
            hours: "24時間",
            phone: "119（緊急）/ 047-452-1283（代表）",
            website: "https://www.city.narashino.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 10
        },
        {
            id: 21,
            name: "谷津遊路公園（避難場所）",
            category: "disaster",
            lat: 35.6805,
            lng: 140.0195,
            description: "一時避難場所として指定されている公園です。",
            icon: "🟢",
            address: "千葉県習志野市谷津5丁目",
            hours: "24時間開放",
            phone: "047-451-1151（市役所）",
            website: "https://www.city.narashino.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '津田沼',
            walkingMinutes: 7
        },

        // ========== 千葉駅エリア ==========
        {
            id: 22,
            name: "千葉駅（JR総武線）",
            category: "station",
            lat: 35.6073,
            lng: 140.1063,
            description: "千葉県の中心駅。総武線、総武快速線、成田線、外房線、内房線が乗り入れ。",
            icon: "🚉",
            address: "千葉県千葉市中央区新千葉1丁目",
            hours: "始発〜終電",
            phone: "043-222-0145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '千葉',
            walkingMinutes: 0
        },
        {
            id: 23,
            name: "ペリエ千葉",
            category: "shopping",
            lat: 35.6075,
            lng: 140.1065,
            description: "千葉駅直結の大型駅ビル。ファッション、雑貨、グルメが充実。",
            icon: "🏬",
            address: "千葉県千葉市中央区新千葉1-1-1",
            hours: "10:00〜21:00（店舗により異なる）",
            phone: "043-227-8201",
            website: "https://www.perie.co.jp/chiba/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '千葉',
            walkingMinutes: 1
        },
        {
            id: 24,
            name: "そごう千葉店",
            category: "shopping",
            lat: 35.6089,
            lng: 140.1075,
            description: "老舗百貨店。品質の高い商品とサービスを提供。",
            icon: "🛍️",
            address: "千葉県千葉市中央区新町1000",
            hours: "10:00〜20:00",
            phone: "043-245-2111",
            website: "https://www.sogo-seibu.jp/chiba/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '千葉',
            walkingMinutes: 3
        },
        {
            id: 25,
            name: "千葉市役所",
            category: "public",
            lat: 35.6063,
            lng: 140.1124,
            description: "千葉市の行政機関。市民サービスを提供。",
            icon: "🏛️",
            address: "千葉県千葉市中央区千葉港1-1",
            hours: "月〜金 8:30〜17:30",
            phone: "043-245-5111",
            website: "https://www.city.chiba.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '千葉',
            walkingMinutes: 12
        },
        {
            id: 26,
            name: "千葉公園",
            category: "park",
            lat: 35.6178,
            lng: 140.1189,
            description: "広大な都市公園。ボート池や日本庭園があります。",
            icon: "🌳",
            address: "千葉県千葉市中央区弁天3-1-1",
            hours: "24時間開放",
            phone: "043-251-5103",
            website: "https://www.city.chiba.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '千葉',
            walkingMinutes: 15
        },

        // ========== 西千葉駅エリア ==========
        {
            id: 27,
            name: "西千葉駅（JR総武線）",
            category: "station",
            lat: 35.6233,
            lng: 140.1064,
            description: "千葉大学の最寄り駅。学生街として栄えています。",
            icon: "🚉",
            address: "千葉県千葉市中央区春日2丁目",
            hours: "始発〜終電",
            phone: "043-222-0145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '西千葉',
            walkingMinutes: 0
        },
        {
            id: 28,
            name: "千葉大学 西千葉キャンパス",
            category: "education",
            lat: 35.6269,
            lng: 140.1036,
            description: "国立大学法人千葉大学の本部キャンパス。",
            icon: "🎓",
            address: "千葉県千葉市稲毛区弥生町1-33",
            hours: "平日 8:30〜17:15",
            phone: "043-251-1111",
            website: "https://www.chiba-u.ac.jp/",
            lines: ['sobuLocal'],
            nearestStation: '西千葉',
            walkingMinutes: 5
        },

        // ========== 稲毛駅エリア ==========
        {
            id: 29,
            name: "稲毛駅（JR総武線）",
            category: "station",
            lat: 35.6331,
            lng: 140.1059,
            description: "快速停車駅。住宅街と商業エリアが共存する地域。",
            icon: "🚉",
            address: "千葉県千葉市稲毛区稲毛東3丁目",
            hours: "始発〜終電",
            phone: "043-222-0145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '稲毛',
            walkingMinutes: 0
        },
        {
            id: 30,
            name: "ペリエ稲毛",
            category: "shopping",
            lat: 35.6332,
            lng: 140.1060,
            description: "稲毛駅直結のショッピングセンター。",
            icon: "🏬",
            address: "千葉県千葉市稲毛区稲毛東3-19-11",
            hours: "10:00〜21:00",
            phone: "043-307-8201",
            website: "https://www.perie.co.jp/inage/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '稲毛',
            walkingMinutes: 1
        },
        {
            id: 31,
            name: "稲毛浅間神社",
            category: "public",
            lat: 35.6398,
            lng: 140.0958,
            description: "歴史ある神社。初詣や祭りで賑わいます。",
            icon: "⛩️",
            address: "千葉県千葉市稲毛区稲毛1-15-10",
            hours: "参拝自由",
            phone: "043-245-7777",
            website: "https://www.sengenjinja.info/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '稲毛',
            walkingMinutes: 10
        },

        // ========== 新検見川駅エリア ==========
        {
            id: 32,
            name: "新検見川駅（JR総武線）",
            category: "station",
            lat: 35.6462,
            lng: 140.0867,
            description: "住宅地に位置する駅。地域密着型の商店街がある。",
            icon: "🚉",
            address: "千葉県千葉市花見川区南花園2丁目",
            hours: "始発〜終電",
            phone: "043-222-0145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '新検見川',
            walkingMinutes: 0
        },
        {
            id: 33,
            name: "イオン新検見川店",
            category: "shopping",
            lat: 35.6455,
            lng: 140.0875,
            description: "地域密着型のスーパーマーケット。",
            icon: "🏬",
            address: "千葉県千葉市花見川区花園1-8-1",
            hours: "9:00〜22:00",
            phone: "043-250-3011",
            website: "https://www.aeon.com/",
            lines: ['sobuLocal'],
            nearestStation: '新検見川',
            walkingMinutes: 3
        },

        // ========== 幕張駅エリア ==========
        {
            id: 34,
            name: "幕張駅（JR総武線）",
            category: "station",
            lat: 35.6577,
            lng: 140.0506,
            description: "幕張エリアの玄関口。幕張メッセへのアクセス拠点。",
            icon: "🚉",
            address: "千葉県千葉市花見川区幕張町5丁目",
            hours: "始発〜終電",
            phone: "043-222-0145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '幕張',
            walkingMinutes: 0
        },
        {
            id: 35,
            name: "幕張メッセ",
            category: "public",
            lat: 35.6481,
            lng: 140.0343,
            description: "日本最大級のコンベンション施設。展示会やイベントを開催。",
            icon: "🏢",
            address: "千葉県千葉市美浜区中瀬2-1",
            hours: "イベントにより異なる",
            phone: "043-296-0001",
            website: "https://www.m-messe.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '幕張',
            walkingMinutes: 20
        },

        // ========== 幕張本郷駅エリア ==========
        {
            id: 36,
            name: "幕張本郷駅（JR総武線）",
            category: "station",
            lat: 35.6699,
            lng: 140.0539,
            description: "京成線も乗り入れる駅。住宅街の中心。",
            icon: "🚉",
            address: "千葉県千葉市花見川区幕張本郷1丁目",
            hours: "始発〜終電",
            phone: "043-222-0145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '幕張本郷',
            walkingMinutes: 0
        },
        {
            id: 37,
            name: "ワンズモール",
            category: "shopping",
            lat: 35.6705,
            lng: 140.0550,
            description: "地域最大級のショッピングモール。専門店が多数入居。",
            icon: "🏬",
            address: "千葉県千葉市花見川区幕張本郷2-25-1",
            hours: "10:00〜21:00",
            phone: "043-350-9000",
            website: "https://www.ones-mall.jp/",
            lines: ['sobuLocal'],
            nearestStation: '幕張本郷',
            walkingMinutes: 3
        },

        // ========== 船橋駅エリア ==========
        {
            id: 38,
            name: "船橋駅（JR総武線）",
            category: "station",
            lat: 35.6954,
            lng: 139.9848,
            description: "船橋市の中心駅。総武線、総武快速線、東武線が乗り入れ。",
            icon: "🚉",
            address: "千葉県船橋市本町7丁目",
            hours: "始発〜終電",
            phone: "047-424-2727",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '船橋',
            walkingMinutes: 0
        },
        {
            id: 39,
            name: "東武百貨店 船橋店",
            category: "shopping",
            lat: 35.6958,
            lng: 139.9845,
            description: "船橋駅直結の百貨店。幅広い商品を取り扱い。",
            icon: "🛍️",
            address: "千葉県船橋市本町7-1-1",
            hours: "10:00〜20:00",
            phone: "047-425-2211",
            website: "https://www.tobu-dept.jp/funabashi/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '船橋',
            walkingMinutes: 1
        },
        {
            id: 40,
            name: "シャポー船橋",
            category: "shopping",
            lat: 35.6955,
            lng: 139.9850,
            description: "駅ナカ商業施設。食品や雑貨が充実。",
            icon: "🏢",
            address: "千葉県船橋市本町7-1-1",
            hours: "10:00〜21:00",
            phone: "047-460-0222",
            website: "https://www.shapo-funabashi.com/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '船橋',
            walkingMinutes: 1
        },
        {
            id: 41,
            name: "船橋市役所",
            category: "public",
            lat: 35.6941,
            lng: 139.9832,
            description: "船橋市の行政機関。各種手続きが可能。",
            icon: "🏛️",
            address: "千葉県船橋市湊町2-10-25",
            hours: "月〜金 9:00〜17:00",
            phone: "047-436-2111",
            website: "https://www.city.funabashi.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '船橋',
            walkingMinutes: 5
        },
        {
            id: 42,
            name: "船橋アリーナ",
            category: "public",
            lat: 35.7021,
            lng: 139.9937,
            description: "スポーツイベントやコンサートが開催される多目的施設。",
            icon: "🏟️",
            address: "千葉県船橋市習志野台7-5-1",
            hours: "イベントにより異なる",
            phone: "047-461-5611",
            website: "https://www.funabashi-arena.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '船橋',
            walkingMinutes: 25
        },

        // ========== 西船橋駅エリア ==========
        {
            id: 43,
            name: "西船橋駅（JR総武線）",
            category: "station",
            lat: 35.7095,
            lng: 139.9589,
            description: "総武線、武蔵野線、東西線、東葉高速線が乗り入れるターミナル駅。",
            icon: "🚉",
            address: "千葉県船橋市西船4丁目",
            hours: "始発〜終電",
            phone: "047-424-2727",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '西船橋',
            walkingMinutes: 0
        },
        {
            id: 44,
            name: "東武ストア 西船橋店",
            category: "shopping",
            lat: 35.7098,
            lng: 139.9592,
            description: "駅直結のスーパーマーケット。日常の買い物に便利。",
            icon: "🏬",
            address: "千葉県船橋市西船4-27-7",
            hours: "10:00〜22:00",
            phone: "047-495-1711",
            website: "https://www.tobustore.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '西船橋',
            walkingMinutes: 2
        },

        // ========== 下総中山駅エリア ==========
        {
            id: 45,
            name: "下総中山駅（JR総武線）",
            category: "station",
            lat: 35.7189,
            lng: 139.9334,
            description: "中山法華経寺の最寄り駅。京成線も利用可能。",
            icon: "🚉",
            address: "千葉県船橋市本中山3丁目",
            hours: "始発〜終電",
            phone: "047-424-2727",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '下総中山',
            walkingMinutes: 0
        },
        {
            id: 46,
            name: "中山法華経寺",
            category: "public",
            lat: 35.7235,
            lng: 139.9312,
            description: "日蓮宗の大本山。国宝や重要文化財を多数所蔵。",
            icon: "⛩️",
            address: "千葉県市川市中山2-10-1",
            hours: "参拝自由",
            phone: "047-334-3433",
            website: "https://www.hokekyoji.com/",
            lines: ['sobuLocal'],
            nearestStation: '下総中山',
            walkingMinutes: 8
        },

        // ========== 本八幡駅エリア ==========
        {
            id: 47,
            name: "本八幡駅（JR総武線）",
            category: "station",
            lat: 35.7222,
            lng: 139.9255,
            description: "市川市の中心駅。都営新宿線も乗り入れ。",
            icon: "🚉",
            address: "千葉県市川市八幡3丁目",
            hours: "始発〜終電",
            phone: "047-332-2145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '本八幡',
            walkingMinutes: 0
        },
        {
            id: 48,
            name: "シャポー本八幡",
            category: "shopping",
            lat: 35.7224,
            lng: 139.9258,
            description: "駅直結のショッピングセンター。食品や雑貨が充実。",
            icon: "🏢",
            address: "千葉県市川市八幡3-3-1",
            hours: "10:00〜21:00",
            phone: "047-370-0222",
            website: "https://www.shapo-motoyawata.com/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '本八幡',
            walkingMinutes: 1
        },
        {
            id: 49,
            name: "ニッケコルトンプラザ",
            category: "shopping",
            lat: 35.7188,
            lng: 139.9177,
            description: "大型ショッピングモール。映画館やレストラン街も併設。",
            icon: "🏬",
            address: "千葉県市川市鬼高1-1-1",
            hours: "10:00〜21:00（店舗により異なる）",
            phone: "047-378-3551",
            website: "https://www.nikke-coltonplaza.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '本八幡',
            walkingMinutes: 12
        },
        {
            id: 50,
            name: "市川市役所",
            category: "public",
            lat: 35.7215,
            lng: 139.9306,
            description: "市川市の行政機関。市民サービスを提供。",
            icon: "🏛️",
            address: "千葉県市川市南八幡2-20-2",
            hours: "月〜金 8:45〜17:15",
            phone: "047-334-1111",
            website: "https://www.city.ichikawa.lg.jp/",
            lines: ['sobuLocal', 'sobuRapid'],
            nearestStation: '本八幡',
            walkingMinutes: 3
        },

        // ========== 市川駅エリア ==========
        {
            id: 51,
            name: "市川駅（JR総武線）",
            category: "station",
            lat: 35.7222,
            lng: 139.9308,
            description: "市川市の代表駅。京成線市川真間駅へのアクセスも便利。",
            icon: "🚉",
            address: "千葉県市川市市川1丁目",
            hours: "始発〜終電",
            phone: "047-332-2145",
            website: "https://www.jreast.co.jp/",
            lines: ['sobuLocal'],
            nearestStation: '市川',
            walkingMinutes: 0
        },
        {
            id: 52,
            name: "シャポー市川",
            category: "shopping",
            lat: 35.7224,
            lng: 139.9310,
            description: "市川駅直結のショッピング施設。",
            icon: "🏢",
            address: "千葉県市川市市川1-4-10",
            hours: "10:00〜21:00",
            phone: "047-322-0222",
            website: "https://www.shapo-ichikawa.com/",
            lines: ['sobuLocal'],
            nearestStation: '市川',
            walkingMinutes: 1
        },
        {
            id: 53,
            name: "市川市文化会館",
            category: "public",
            lat: 35.7198,
            lng: 139.9295,
            description: "コンサートや演劇が開催される文化施設。",
            icon: "🎭",
            address: "千葉県市川市大和田1-1-5",
            hours: "9:00〜22:00",
            phone: "047-379-5111",
            website: "https://www.tekona.net/bunka/",
            lines: ['sobuRapid'],
            nearestStation: '本八幡',
            walkingMinutes: 5
        },

        // ========== 山手線エリア ==========
        // 新宿駅周辺
        {
            id: 54,
            name: "ルミネエスト新宿",
            category: "shopping",
            lat: 35.6911,
            lng: 139.7006,
            description: "新宿駅直結のファッションビル。若者向けブランドが充実。",
            icon: "🏬",
            address: "東京都新宿区新宿3-38-1",
            hours: "11:00〜21:30",
            phone: "03-5269-1111",
            website: "https://www.lumine.ne.jp/est/",
            lines: ['yamanote', 'chuoRapid', 'sobuLocal'],
            nearestStation: '新宿',
            walkingMinutes: 1
        },
        {
            id: 55,
            name: "新宿高島屋",
            category: "shopping",
            lat: 35.6897,
            lng: 139.6994,
            description: "老舗百貨店。高級ブランドから食品まで幅広く展開。",
            icon: "🛍️",
            address: "東京都渋谷区千駄ヶ谷5-24-2",
            hours: "10:00〜20:00",
            phone: "03-5361-1111",
            website: "https://www.takashimaya.co.jp/shinjuku/",
            lines: ['yamanote', 'chuoRapid', 'sobuLocal'],
            nearestStation: '新宿',
            walkingMinutes: 3
        },
        {
            id: 56,
            name: "都立新宿高等学校",
            category: "highschool",
            lat: 35.6847,
            lng: 139.7083,
            description: "都立の進学校。文武両道を掲げる伝統校。",
            icon: "🏫",
            address: "東京都新宿区内藤町11-4",
            hours: "平日 8:30〜17:00",
            phone: "03-3354-7411",
            website: "https://www.metro.ed.jp/shinjuku-h/",
            lines: ['yamanote'],
            nearestStation: '新宿',
            walkingMinutes: 10
        },

        // 渋谷駅周辺
        {
            id: 57,
            name: "渋谷スクランブルスクエア",
            category: "shopping",
            lat: 35.6585,
            lng: 139.7024,
            description: "渋谷駅直結の高層複合施設。展望台SHIBUYA SKYも人気。",
            icon: "🏢",
            address: "東京都渋谷区渋谷2-24-12",
            hours: "10:00〜21:00（店舗により異なる）",
            phone: "03-4221-0229",
            website: "https://www.shibuya-scramble-square.com/",
            lines: ['yamanote'],
            nearestStation: '渋谷',
            walkingMinutes: 1
        },
        {
            id: 58,
            name: "渋谷109",
            category: "shopping",
            lat: 35.6595,
            lng: 139.6985,
            description: "若者のファッションの聖地。トレンドの発信地。",
            icon: "🛍️",
            address: "東京都渋谷区道玄坂2-29-1",
            hours: "10:00〜21:00",
            phone: "03-3477-5111",
            website: "https://www.shibuya109.jp/",
            lines: ['yamanote'],
            nearestStation: '渋谷',
            walkingMinutes: 2
        },

        // 池袋駅周辺
        {
            id: 59,
            name: "池袋駅（JR山手線）",
            category: "station",
            lat: 35.7295,
            lng: 139.7109,
            description: "山手線の主要駅。埼玉方面への玄関口。",
            icon: "🚉",
            address: "東京都豊島区南池袋1丁目",
            hours: "始発〜終電",
            phone: "03-3981-2111",
            website: "https://www.jreast.co.jp/",
            lines: ['yamanote'],
            nearestStation: '池袋',
            walkingMinutes: 0
        },
        {
            id: 60,
            name: "サンシャインシティ",
            category: "shopping",
            lat: 35.7295,
            lng: 139.7188,
            description: "大型複合商業施設。水族館、展望台、ショップが充実。",
            icon: "🏬",
            address: "東京都豊島区東池袋3-1-1",
            hours: "10:00〜20:00（施設により異なる）",
            phone: "03-3989-3331",
            website: "https://sunshinecity.jp/",
            lines: ['yamanote'],
            nearestStation: '池袋',
            walkingMinutes: 8
        },
        {
            id: 61,
            name: "立教大学 池袋キャンパス",
            category: "education",
            lat: 35.7318,
            lng: 139.7179,
            description: "私立大学。歴史ある赤レンガ校舎が有名。",
            icon: "🎓",
            address: "東京都豊島区西池袋3-34-1",
            hours: "平日 8:00〜22:00",
            phone: "03-3985-2202",
            website: "https://www.rikkyo.ac.jp/",
            lines: ['yamanote'],
            nearestStation: '池袋',
            walkingMinutes: 7
        },

        // 上野駅周辺
        {
            id: 62,
            name: "上野駅（JR山手線）",
            category: "station",
            lat: 35.7138,
            lng: 139.7774,
            description: "北関東・東北方面への玄関口。新幹線も発着。",
            icon: "🚉",
            address: "東京都台東区上野7丁目",
            hours: "始発〜終電",
            phone: "03-3841-8411",
            website: "https://www.jreast.co.jp/",
            lines: ['yamanote', 'takasaki'],
            nearestStation: '上野',
            walkingMinutes: 0
        },
        {
            id: 63,
            name: "アメヤ横丁",
            category: "shopping",
            lat: 35.7089,
            lng: 139.7753,
            description: "活気あふれる商店街。食品、衣料品、雑貨が格安。",
            icon: "🛍️",
            address: "東京都台東区上野4-6-5",
            hours: "10:00〜19:00（店舗により異なる）",
            phone: "03-3832-5053",
            website: "https://www.ameyoko.net/",
            lines: ['yamanote'],
            nearestStation: '上野',
            walkingMinutes: 2
        },
        {
            id: 64,
            name: "上野公園",
            category: "park",
            lat: 35.7148,
            lng: 139.7740,
            description: "広大な都市公園。博物館、動物園、美術館が隣接。",
            icon: "🌳",
            address: "東京都台東区上野公園",
            hours: "5:00〜23:00",
            phone: "03-3828-5644",
            website: "https://www.kensetsu.metro.tokyo.lg.jp/",
            lines: ['yamanote'],
            nearestStation: '上野',
            walkingMinutes: 2
        },

        // 東京駅周辺
        {
            id: 65,
            name: "東京駅（JR山手線）",
            category: "station",
            lat: 35.6812,
            lng: 139.7671,
            description: "日本の鉄道網の中心駅。新幹線の起点。",
            icon: "🚉",
            address: "東京都千代田区丸の内1丁目",
            hours: "始発〜終電",
            phone: "03-3212-2111",
            website: "https://www.jreast.co.jp/",
            lines: ['yamanote', 'chuoRapid', 'sobuRapid', 'takasaki'],
            nearestStation: '東京',
            walkingMinutes: 0
        },
        {
            id: 66,
            name: "大丸東京店",
            category: "shopping",
            lat: 35.6809,
            lng: 139.7651,
            description: "東京駅直結の百貨店。お土産も充実。",
            icon: "🛍️",
            address: "東京都千代田区丸の内1-9-1",
            hours: "10:00〜20:00",
            phone: "03-3212-8011",
            website: "https://www.daimaru.co.jp/tokyo/",
            lines: ['yamanote', 'chuoRapid'],
            nearestStation: '東京',
            walkingMinutes: 1
        },

        // 品川駅周辺
        {
            id: 67,
            name: "品川駅（JR山手線）",
            category: "station",
            lat: 35.6284,
            lng: 139.7387,
            description: "東海道新幹線の停車駅。羽田空港へのアクセスも便利。",
            icon: "🚉",
            address: "東京都港区高輪3丁目",
            hours: "始発〜終電",
            phone: "03-3444-4761",
            website: "https://www.jreast.co.jp/",
            lines: ['yamanote', 'sobuRapid'],
            nearestStation: '品川',
            walkingMinutes: 0
        },
        {
            id: 68,
            name: "アトレ品川",
            category: "shopping",
            lat: 35.6286,
            lng: 139.7389,
            description: "品川駅直結のショッピングセンター。",
            icon: "🏢",
            address: "東京都港区港南2-18-1",
            hours: "10:00〜21:00",
            phone: "03-6717-0900",
            website: "https://www.atre.co.jp/shinagawa/",
            lines: ['yamanote'],
            nearestStation: '品川',
            walkingMinutes: 1
        },

        // ========== 中央線エリア ==========
        // 吉祥寺駅周辺
        {
            id: 69,
            name: "吉祥寺駅（JR中央線）",
            category: "station",
            lat: 35.7031,
            lng: 139.5796,
            description: "住みたい街ランキング上位常連。商業施設が充実。",
            icon: "🚉",
            address: "東京都武蔵野市吉祥寺南町1丁目",
            hours: "始発〜終電",
            phone: "0422-22-2115",
            website: "https://www.jreast.co.jp/",
            lines: ['chuoRapid', 'sobuLocal'],
            nearestStation: '吉祥寺',
            walkingMinutes: 0
        },
        {
            id: 70,
            name: "吉祥寺パルコ",
            category: "shopping",
            lat: 35.7028,
            lng: 139.5801,
            description: "ファッションと雑貨の人気スポット。",
            icon: "🛍️",
            address: "東京都武蔵野市吉祥寺本町1-5-1",
            hours: "10:00〜21:00",
            phone: "0422-21-8111",
            website: "https://kichijoji.parco.jp/",
            lines: ['chuoRapid'],
            nearestStation: '吉祥寺',
            walkingMinutes: 2
        },
        {
            id: 71,
            name: "井の頭恩賜公園",
            category: "park",
            lat: 35.7005,
            lng: 139.5737,
            description: "広大な公園。ボート池と自然が楽しめる。",
            icon: "🌳",
            address: "東京都武蔵野市御殿山1-18-31",
            hours: "24時間開放",
            phone: "0422-47-6900",
            website: "https://www.kensetsu.metro.tokyo.lg.jp/",
            lines: ['chuoRapid'],
            nearestStation: '吉祥寺',
            walkingMinutes: 5
        },

        // 中野駅周辺
        {
            id: 72,
            name: "中野駅（JR中央線）",
            category: "station",
            lat: 35.7058,
            lng: 139.6656,
            description: "サブカルチャーの街。中野ブロードウェイが有名。",
            icon: "🚉",
            address: "東京都中野区中野5丁目",
            hours: "始発〜終電",
            phone: "03-3389-1111",
            website: "https://www.jreast.co.jp/",
            lines: ['chuoRapid', 'sobuLocal'],
            nearestStation: '中野',
            walkingMinutes: 0
        },
        {
            id: 73,
            name: "中野ブロードウェイ",
            category: "shopping",
            lat: 35.7065,
            lng: 139.6641,
            description: "サブカルチャーの聖地。アニメ・マンガグッズが充実。",
            icon: "🏢",
            address: "東京都中野区中野5-52-15",
            hours: "12:00〜20:00（店舗により異なる）",
            phone: "03-3388-7004",
            website: "https://www.nbw.jp/",
            lines: ['chuoRapid'],
            nearestStation: '中野',
            walkingMinutes: 5
        },

        // 立川駅周辺
        {
            id: 74,
            name: "立川駅（JR中央線）",
            category: "station",
            lat: 35.6977,
            lng: 139.4137,
            description: "多摩地区の中心駅。商業施設が集積。",
            icon: "🚉",
            address: "東京都立川市曙町2丁目",
            hours: "始発〜終電",
            phone: "042-523-3461",
            website: "https://www.jreast.co.jp/",
            lines: ['chuoRapid'],
            nearestStation: '立川',
            walkingMinutes: 0
        },
        {
            id: 75,
            name: "ルミネ立川",
            category: "shopping",
            lat: 35.6979,
            lng: 139.4139,
            description: "立川駅直結のショッピングセンター。",
            icon: "🏬",
            address: "東京都立川市曙町2-1-1",
            hours: "10:00〜21:00",
            phone: "042-527-8211",
            website: "https://www.lumine.ne.jp/tachikawa/",
            lines: ['chuoRapid'],
            nearestStation: '立川',
            walkingMinutes: 1
        },
        {
            id: 76,
            name: "昭和記念公園",
            category: "park",
            lat: 35.6976,
            lng: 139.4055,
            description: "広大な国営公園。四季折々の花が楽しめる。",
            icon: "🌳",
            address: "東京都立川市緑町3173",
            hours: "9:30〜17:00（季節により変動）",
            phone: "042-528-1751",
            website: "https://www.showakinen-koen.jp/",
            lines: ['chuoRapid'],
            nearestStation: '立川',
            walkingMinutes: 10
        },

        // 八王子駅周辺
        {
            id: 77,
            name: "八王子駅（JR中央線）",
            category: "station",
            lat: 35.6559,
            lng: 139.3389,
            description: "八王子市の中心駅。学生が多い街。",
            icon: "🚉",
            address: "東京都八王子市旭町1-1",
            hours: "始発〜終電",
            phone: "042-622-4819",
            website: "https://www.jreast.co.jp/",
            lines: ['chuoRapid'],
            nearestStation: '八王子',
            walkingMinutes: 0
        },
        {
            id: 78,
            name: "セレオ八王子",
            category: "shopping",
            lat: 35.6561,
            lng: 139.3391,
            description: "八王子駅直結のショッピングセンター。",
            icon: "🏢",
            address: "東京都八王子市旭町1-1",
            hours: "10:00〜21:00",
            phone: "042-686-3111",
            website: "https://www.celeo.co.jp/hachioji/",
            lines: ['chuoRapid'],
            nearestStation: '八王子',
            walkingMinutes: 1
        },
        {
            id: 79,
            name: "都立八王子東高等学校",
            category: "highschool",
            lat: 35.6648,
            lng: 139.3515,
            description: "都立の進学校。部活動も盛ん。",
            icon: "🏫",
            address: "東京都八王子市高倉町68-1",
            hours: "平日 8:30〜17:00",
            phone: "042-673-5611",
            website: "https://www.metro.ed.jp/hachiojihigashi-h/",
            lines: ['chuoRapid'],
            nearestStation: '八王子',
            walkingMinutes: 15
        },

        // ========== 高崎線エリア ==========
        // 大宮駅周辺
        {
            id: 80,
            name: "大宮駅（JR高崎線）",
            category: "station",
            lat: 35.9063,
            lng: 139.6239,
            description: "埼玉県の交通の要衝。新幹線も発着。",
            icon: "🚉",
            address: "埼玉県さいたま市大宮区錦町630",
            hours: "始発〜終電",
            phone: "048-642-2560",
            website: "https://www.jreast.co.jp/",
            lines: ['takasaki'],
            nearestStation: '大宮',
            walkingMinutes: 0
        },
        {
            id: 81,
            name: "ルミネ大宮",
            category: "shopping",
            lat: 35.9065,
            lng: 139.6241,
            description: "大宮駅直結のショッピングセンター。",
            icon: "🏬",
            address: "埼玉県さいたま市大宮区錦町630",
            hours: "10:00〜21:00",
            phone: "048-645-1211",
            website: "https://www.lumine.ne.jp/omiya/",
            lines: ['takasaki'],
            nearestStation: '大宮',
            walkingMinutes: 1
        },
        {
            id: 82,
            name: "さいたまスーパーアリーナ",
            category: "public",
            lat: 35.8943,
            lng: 139.6314,
            description: "大規模イベント施設。コンサート、スポーツイベントを開催。",
            icon: "🏟️",
            address: "埼玉県さいたま市中央区新都心8",
            hours: "イベントにより異なる",
            phone: "048-601-1122",
            website: "https://www.saitama-arena.co.jp/",
            lines: ['takasaki'],
            nearestStation: '大宮',
            walkingMinutes: 15
        },

        // 熊谷駅周辺
        {
            id: 83,
            name: "熊谷駅（JR高崎線）",
            category: "station",
            lat: 36.1476,
            lng: 139.3889,
            description: "埼玉県北部の中心駅。夏は日本一の暑さで有名。",
            icon: "🚉",
            address: "埼玉県熊谷市筑波2丁目",
            hours: "始発〜終電",
            phone: "048-521-2851",
            website: "https://www.jreast.co.jp/",
            lines: ['takasaki'],
            nearestStation: '熊谷',
            walkingMinutes: 0
        },
        {
            id: 84,
            name: "埼玉県立熊谷高等学校",
            category: "highschool",
            lat: 36.1425,
            lng: 139.3852,
            description: "県立の伝統ある進学校。応援団が有名。",
            icon: "🏫",
            address: "埼玉県熊谷市宮町2-81",
            hours: "平日 8:30〜17:00",
            phone: "048-521-0015",
            website: "https://kumagaya-h.spec.ed.jp/",
            lines: ['takasaki'],
            nearestStation: '熊谷',
            walkingMinutes: 10
        },

        // ========== その他の高等学校 ==========
        {
            id: 85,
            name: "都立戸山高等学校",
            category: "highschool",
            lat: 35.7012,
            lng: 139.7103,
            description: "都立の名門進学校。早稲田大学近く。",
            icon: "🏫",
            address: "東京都新宿区戸山3-19-1",
            hours: "平日 8:30〜17:00",
            phone: "03-3202-4301",
            website: "https://www.metro.ed.jp/toyama-h/",
            lines: ['yamanote'],
            nearestStation: '新宿',
            walkingMinutes: 20
        },
        {
            id: 86,
            name: "都立西高等学校",
            category: "highschool",
            lat: 35.6711,
            lng: 139.5744,
            description: "都立トップクラスの進学校。",
            icon: "🏫",
            address: "東京都杉並区宮前4-21-32",
            hours: "平日 8:30〜17:00",
            phone: "03-3333-7771",
            website: "https://www.metro.ed.jp/nishi-h/",
            lines: ['chuoRapid'],
            nearestStation: '吉祥寺',
            walkingMinutes: 20
        },
        {
            id: 87,
            name: "千葉県立千葉高等学校",
            category: "highschool",
            lat: 35.6046,
            lng: 140.1149,
            description: "県立の名門進学校。千葉県トップレベル。",
            icon: "🏫",
            address: "千葉県千葉市中央区葛城1-5-2",
            hours: "平日 8:30〜17:00",
            phone: "043-227-7434",
            website: "https://cms1.chiba-c.ed.jp/chiba-h/",
            lines: ['sobuRapid', 'sobuLocal'],
            nearestStation: '千葉',
            walkingMinutes: 15
        },
        {
            id: 88,
            name: "千葉県立船橋高等学校",
            category: "highschool",
            lat: 35.7058,
            lng: 140.0025,
            description: "県立の名門進学校。部活動も盛ん。",
            icon: "🏫",
            address: "千葉県船橋市東船橋6-1-1",
            hours: "平日 8:30〜17:00",
            phone: "047-422-2188",
            website: "https://cms1.chiba-c.ed.jp/funabashi-h/",
            lines: ['sobuRapid', 'sobuLocal'],
            nearestStation: '船橋',
            walkingMinutes: 20
        },

        // ========== 東京都の主要大学 ==========
        {
            id: 89,
            name: "東京大学 本郷キャンパス",
            category: "education",
            lat: 35.7128,
            lng: 139.7628,
            description: "日本を代表する国立大学。",
            icon: "🎓",
            address: "東京都文京区本郷7-3-1",
            hours: "平日 8:30〜17:15",
            phone: "03-3812-2111",
            website: "https://www.u-tokyo.ac.jp/",
            lines: ['yamanote'],
            nearestStation: '本郷三丁目',
            walkingMinutes: 8
        },
        {
            id: 90,
            name: "早稲田大学 早稲田キャンパス",
            category: "education",
            lat: 35.7090,
            lng: 139.7198,
            description: "私立大学の雄。学問の自由を尊重。",
            icon: "🎓",
            address: "東京都新宿区西早稲田1-6-1",
            hours: "平日 8:30〜18:00",
            phone: "03-3203-4141",
            website: "https://www.waseda.jp/",
            lines: ['yamanote'],
            nearestStation: '高田馬場',
            walkingMinutes: 15
        },
        {
            id: 91,
            name: "慶應義塾大学 三田キャンパス",
            category: "education",
            lat: 35.6500,
            lng: 139.7425,
            description: "伝統ある私立大学。実学を重視。",
            icon: "🎓",
            address: "東京都港区三田2-15-45",
            hours: "平日 8:30〜18:00",
            phone: "03-5427-1517",
            website: "https://www.keio.ac.jp/",
            lines: ['yamanote', 'keihinTohoku'],
            nearestStation: '田町',
            walkingMinutes: 8
        },
        {
            id: 92,
            name: "明治大学 駿河台キャンパス",
            category: "education",
            lat: 35.6999,
            lng: 139.7659,
            description: "MARCH の一角。多様な学部を擁する。",
            icon: "🎓",
            address: "東京都千代田区神田駿河台1-1",
            hours: "平日 8:30〜18:00",
            phone: "03-3296-4545",
            website: "https://www.meiji.ac.jp/",
            lines: ['sobuLocal', 'chuoRapid'],
            nearestStation: '御茶ノ水',
            walkingMinutes: 3
        },
        {
            id: 93,
            name: "法政大学 市ヶ谷キャンパス",
            category: "education",
            lat: 35.6942,
            lng: 139.7434,
            description: "自由と進歩の学風。都心の一等地に位置。",
            icon: "🎓",
            address: "東京都千代田区富士見2-17-1",
            hours: "平日 8:30〜18:00",
            phone: "03-3264-9240",
            website: "https://www.hosei.ac.jp/",
            lines: ['sobuLocal', 'chuoRapid'],
            nearestStation: '市ヶ谷',
            walkingMinutes: 5
        },
        {
            id: 94,
            name: "中央大学 後楽園キャンパス",
            category: "education",
            lat: 35.7024,
            lng: 139.7527,
            description: "理工学部のキャンパス。最新設備が充実。",
            icon: "🎓",
            address: "東京都文京区春日1-13-27",
            hours: "平日 8:30〜18:00",
            phone: "03-3817-1717",
            website: "https://www.chuo-u.ac.jp/",
            lines: ['yamanote'],
            nearestStation: '後楽園',
            walkingMinutes: 5
        },
        {
            id: 95,
            name: "立教大学 池袋キャンパス",
            category: "education",
            lat: 35.7328,
            lng: 139.7197,
            description: "美しいキャンパスで知られる伝統校。",
            icon: "🎓",
            address: "東京都豊島区西池袋3-34-1",
            hours: "平日 8:30〜18:00",
            phone: "03-3985-2201",
            website: "https://www.rikkyo.ac.jp/",
            lines: ['yamanote', 'saikyo'],
            nearestStation: '池袋',
            walkingMinutes: 7
        },
        {
            id: 96,
            name: "青山学院大学 青山キャンパス",
            category: "education",
            lat: 35.6636,
            lng: 139.7147,
            description: "おしゃれなキャンパス。国際性を重視。",
            icon: "🎓",
            address: "東京都渋谷区渋谷4-4-25",
            hours: "平日 8:30〜18:00",
            phone: "03-3409-8111",
            website: "https://www.aoyama.ac.jp/",
            lines: ['yamanote'],
            nearestStation: '渋谷',
            walkingMinutes: 10
        },
        {
            id: 97,
            name: "東京理科大学 神楽坂キャンパス",
            category: "education",
            lat: 35.7018,
            lng: 139.7413,
            description: "理工系の名門。実力主義の教育。",
            icon: "🎓",
            address: "東京都新宿区神楽坂1-3",
            hours: "平日 8:30〜18:00",
            phone: "03-3260-4271",
            website: "https://www.tus.ac.jp/",
            lines: ['sobuLocal'],
            nearestStation: '飯田橋',
            walkingMinutes: 3
        },
        {
            id: 98,
            name: "上智大学 四谷キャンパス",
            category: "education",
            lat: 35.6837,
            lng: 139.7336,
            description: "カトリック系の名門。語学教育に定評。",
            icon: "🎓",
            address: "東京都千代田区紀尾井町7-1",
            hours: "平日 8:30〜18:00",
            phone: "03-3238-3111",
            website: "https://www.sophia.ac.jp/",
            lines: ['sobuLocal', 'chuoRapid'],
            nearestStation: '四ツ谷',
            walkingMinutes: 5
        },
        {
            id: 99,
            name: "東京工業大学 大岡山キャンパス",
            category: "education",
            lat: 35.6056,
            lng: 139.6840,
            description: "理工系最高峰の国立大学。",
            icon: "🎓",
            address: "東京都目黒区大岡山2-12-1",
            hours: "平日 8:30〜17:15",
            phone: "03-5734-2975",
            website: "https://www.titech.ac.jp/",
            lines: ['tokaido'],
            nearestStation: '大岡山',
            walkingMinutes: 1
        },
        {
            id: 100,
            name: "一橋大学 国立キャンパス",
            category: "education",
            lat: 35.6941,
            lng: 139.4358,
            description: "社会科学系の名門国立大学。",
            icon: "🎓",
            address: "東京都国立市中2-1",
            hours: "平日 8:30〜17:15",
            phone: "042-580-8000",
            website: "https://www.hit-u.ac.jp/",
            lines: ['chuoRapid'],
            nearestStation: '国立',
            walkingMinutes: 10
        },
        {
            id: 101,
            name: "お茶の水女子大学",
            category: "education",
            lat: 35.7193,
            lng: 139.7657,
            description: "国立の女子大学。",
            icon: "🎓",
            address: "東京都文京区大塚2-1-1",
            hours: "平日 8:30〜17:15",
            phone: "03-5978-5111",
            website: "https://www.ocha.ac.jp/",
            lines: ['yamanote'],
            nearestStation: '茗荷谷',
            walkingMinutes: 7
        },
        {
            id: 102,
            name: "東京外国語大学",
            category: "education",
            lat: 35.6776,
            lng: 139.5327,
            description: "外国語・国際関係の専門大学。",
            icon: "🎓",
            address: "東京都府中市朝日町3-11-1",
            hours: "平日 8:30〜17:15",
            phone: "042-330-5111",
            website: "https://www.tufs.ac.jp/",
            lines: ['chuoRapid'],
            nearestStation: '多磨',
            walkingMinutes: 10
        },
        {
            id: 103,
            name: "東京農工大学 小金井キャンパス",
            category: "education",
            lat: 35.7096,
            lng: 139.5108,
            description: "工学部のキャンパス。実践的な教育。",
            icon: "🎓",
            address: "東京都小金井市中町2-24-16",
            hours: "平日 8:30〜17:15",
            phone: "042-388-7003",
            website: "https://www.tuat.ac.jp/",
            lines: ['chuoRapid', 'sobuLocal'],
            nearestStation: '東小金井',
            walkingMinutes: 8
        },
        {
            id: 104,
            name: "電気通信大学",
            category: "education",
            lat: 35.6571,
            lng: 139.5429,
            description: "情報通信技術の専門大学。",
            icon: "🎓",
            address: "東京都調布市調布ケ丘1-5-1",
            hours: "平日 8:30〜17:15",
            phone: "042-443-5000",
            website: "https://www.uec.ac.jp/",
            lines: ['chuoRapid'],
            nearestStation: '調布',
            walkingMinutes: 5
        },
        {
            id: 105,
            name: "東京都立大学 南大沢キャンパス",
            category: "education",
            lat: 35.6141,
            lng: 139.3695,
            description: "都立の総合大学。",
            icon: "🎓",
            address: "東京都八王子市南大沢1-1",
            hours: "平日 8:30〜17:15",
            phone: "042-677-1111",
            website: "https://www.tmu.ac.jp/",
            lines: ['chuoRapid'],
            nearestStation: '南大沢',
            walkingMinutes: 5
        },
        {
            id: 106,
            name: "芝浦工業大学 豊洲キャンパス",
            category: "education",
            lat: 35.6547,
            lng: 139.7960,
            description: "理工系の私立大学。産学連携が盛ん。",
            icon: "🎓",
            address: "東京都江東区豊洲3-7-5",
            hours: "平日 8:30〜18:00",
            phone: "03-5859-7000",
            website: "https://www.shibaura-it.ac.jp/",
            lines: ['keiyo'],
            nearestStation: '豊洲',
            walkingMinutes: 7
        },

        // ========== 神奈川県の主要大学 ==========
        {
            id: 107,
            name: "横浜国立大学",
            category: "education",
            lat: 35.4715,
            lng: 139.5944,
            description: "国立大学。教育・経済・理工が強い。",
            icon: "🎓",
            address: "神奈川県横浜市保土ケ谷区常盤台79-1",
            hours: "平日 8:30〜17:15",
            phone: "045-339-3014",
            website: "https://www.ynu.ac.jp/",
            lines: ['tokaido', 'yokosuka'],
            nearestStation: '保土ケ谷',
            walkingMinutes: 20
        },
        {
            id: 108,
            name: "慶應義塾大学 日吉キャンパス",
            category: "education",
            lat: 35.5531,
            lng: 139.6485,
            description: "慶應の1・2年生が通うキャンパス。",
            icon: "🎓",
            address: "神奈川県横浜市港北区日吉4-1-1",
            hours: "平日 8:30〜18:00",
            phone: "045-563-1111",
            website: "https://www.keio.ac.jp/",
            lines: ['tokaido', 'yokosuka'],
            nearestStation: '日吉',
            walkingMinutes: 1
        },
        {
            id: 109,
            name: "神奈川大学 横浜キャンパス",
            category: "education",
            lat: 35.4979,
            lng: 139.6207,
            description: "総合大学。地域貢献に力を入れる。",
            icon: "🎓",
            address: "神奈川県横浜市神奈川区六角橋3-27-1",
            hours: "平日 8:30〜18:00",
            phone: "045-481-5661",
            website: "https://www.kanagawa-u.ac.jp/",
            lines: ['tokaido', 'keihinTohoku'],
            nearestStation: '横浜',
            walkingMinutes: 25
        },
        {
            id: 110,
            name: "関東学院大学 金沢八景キャンパス",
            category: "education",
            lat: 35.3364,
            lng: 139.6198,
            description: "キリスト教精神に基づく教育。",
            icon: "🎓",
            address: "神奈川県横浜市金沢区六浦東1-50-1",
            hours: "平日 8:30〜18:00",
            phone: "045-786-7002",
            website: "https://www.kanto-gakuin.ac.jp/",
            lines: ['keihinTohoku', 'yokosuka'],
            nearestStation: '金沢八景',
            walkingMinutes: 15
        },
        {
            id: 111,
            name: "横浜市立大学 金沢八景キャンパス",
            category: "education",
            lat: 35.3416,
            lng: 139.6212,
            description: "市立の総合大学。医学部も有する。",
            icon: "🎓",
            address: "神奈川県横浜市金沢区瀬戸22-2",
            hours: "平日 8:30〜17:15",
            phone: "045-787-2311",
            website: "https://www.yokohama-cu.ac.jp/",
            lines: ['keihinTohoku'],
            nearestStation: '金沢八景',
            walkingMinutes: 10
        },

        // ========== 埼玉県の主要大学 ==========
        {
            id: 112,
            name: "埼玉大学",
            category: "education",
            lat: 35.8616,
            lng: 139.6103,
            description: "国立大学。教育・経済・理工が中心。",
            icon: "🎓",
            address: "埼玉県さいたま市桜区下大久保255",
            hours: "平日 8:30〜17:15",
            phone: "048-858-3005",
            website: "https://www.saitama-u.ac.jp/",
            lines: ['keihinTohoku'],
            nearestStation: '南与野',
            walkingMinutes: 20
        },
        {
            id: 113,
            name: "早稲田大学 所沢キャンパス",
            category: "education",
            lat: 35.7955,
            lng: 139.4684,
            description: "スポーツ科学部・人間科学部のキャンパス。",
            icon: "🎓",
            address: "埼玉県所沢市三ケ島2-579-15",
            hours: "平日 8:30〜18:00",
            phone: "04-2947-6702",
            website: "https://www.waseda.jp/",
            lines: ['musashino'],
            nearestStation: '小手指',
            walkingMinutes: 15
        },
        {
            id: 114,
            name: "獨協大学",
            category: "education",
            lat: 35.8932,
            lng: 139.7281,
            description: "外国語教育に定評のある私立大学。",
            icon: "🎓",
            address: "埼玉県草加市学園町1-1",
            hours: "平日 8:30〜18:00",
            phone: "048-946-1900",
            website: "https://www.dokkyo.ac.jp/",
            lines: ['keihinTohoku'],
            nearestStation: '獨協大学前',
            walkingMinutes: 5
        },
        {
            id: 115,
            name: "東京理科大学 野田キャンパス",
            category: "education",
            lat: 35.9561,
            lng: 139.8759,
            description: "理工学部・薬学部のキャンパス。",
            icon: "🎓",
            address: "千葉県野田市山崎2641",
            hours: "平日 8:30〜18:00",
            phone: "04-7124-1501",
            website: "https://www.tus.ac.jp/",
            lines: ['tokaido'],
            nearestStation: '運河',
            walkingMinutes: 5
        },

        // ========== 東京都の主要高校 ==========
        {
            id: 116,
            name: "都立西高等学校",
            category: "highschool",
            lat: 35.6875,
            lng: 139.5963,
            description: "都立トップ校の一つ。自由な校風。",
            icon: "🏫",
            address: "東京都杉並区宮前4-21-32",
            hours: "平日 8:30〜17:00",
            phone: "03-3333-7771",
            website: "http://www.nishi-h.metro.tokyo.jp/",
            lines: ['chuoRapid'],
            nearestStation: '久我山',
            walkingMinutes: 12
        },
        {
            id: 117,
            name: "都立日比谷高等学校",
            category: "highschool",
            lat: 35.6738,
            lng: 139.7523,
            description: "伝統ある都立の名門校。",
            icon: "🏫",
            address: "東京都千代田区永田町2-16-1",
            hours: "平日 8:30〜17:00",
            phone: "03-3581-9176",
            website: "http://www.hibiya-h.metro.tokyo.jp/",
            lines: ['yamanote', 'keihinTohoku'],
            nearestStation: '有楽町',
            walkingMinutes: 15
        },
        {
            id: 118,
            name: "都立国立高等学校",
            category: "highschool",
            lat: 35.6855,
            lng: 139.4398,
            description: "自主自律の精神を重んじる進学校。",
            icon: "🏫",
            address: "東京都国立市東4-25-1",
            hours: "平日 8:30〜17:00",
            phone: "042-575-0126",
            website: "http://www.kunitachi-h.metro.tokyo.jp/",
            lines: ['chuoRapid'],
            nearestStation: '国立',
            walkingMinutes: 10
        },
        {
            id: 119,
            name: "開成高等学校",
            category: "highschool",
            lat: 35.7370,
            lng: 139.7710,
            description: "東大合格者数トップクラスの男子校。",
            icon: "🏫",
            address: "東京都荒川区西日暮里4-2-4",
            hours: "平日 8:30〜17:00",
            phone: "03-3822-0741",
            website: "https://kaiseigakuen.jp/",
            lines: ['yamanote', 'keihinTohoku'],
            nearestStation: '西日暮里',
            walkingMinutes: 3
        },
        {
            id: 120,
            name: "麻布高等学校",
            category: "highschool",
            lat: 35.6522,
            lng: 139.7306,
            description: "自由な校風で知られる男子進学校。",
            icon: "🏫",
            address: "東京都港区元麻布2-3-29",
            hours: "平日 8:30〜17:00",
            phone: "03-3446-6541",
            website: "https://www.azabu-jh.ed.jp/",
            lines: ['yamanote', 'keihinTohoku'],
            nearestStation: '広尾',
            walkingMinutes: 10
        },
        {
            id: 121,
            name: "桜蔭高等学校",
            category: "highschool",
            lat: 35.7030,
            lng: 139.7671,
            description: "女子御三家の一つ。東大合格者多数。",
            icon: "🏫",
            address: "東京都文京区本郷1-5-25",
            hours: "平日 8:30〜17:00",
            phone: "03-3811-0147",
            website: "http://www.oin.ed.jp/",
            lines: ['yamanote'],
            nearestStation: '本郷三丁目',
            walkingMinutes: 5
        },

        // ========== 神奈川県の主要高校 ==========
        {
            id: 122,
            name: "神奈川県立横浜翠嵐高等学校",
            category: "highschool",
            lat: 35.4959,
            lng: 139.6185,
            description: "県立トップ校。自由と規律のバランス。",
            icon: "🏫",
            address: "神奈川県横浜市神奈川区三ツ沢南町1-1",
            hours: "平日 8:30〜17:00",
            phone: "045-311-4621",
            website: "https://www.pen-kanagawa.ed.jp/yokohama-suiran-h/",
            lines: ['keihinTohoku', 'tokaido'],
            nearestStation: '横浜',
            walkingMinutes: 20
        },
        {
            id: 123,
            name: "神奈川県立湘南高等学校",
            category: "highschool",
            lat: 35.3239,
            lng: 139.4884,
            description: "湘南の名門進学校。自由闊達な校風。",
            icon: "🏫",
            address: "神奈川県藤沢市鵠沼神明5-6-10",
            hours: "平日 8:30〜17:00",
            phone: "0466-26-4151",
            website: "https://www.pen-kanagawa.ed.jp/shonan-h/",
            lines: ['tokaido'],
            nearestStation: '藤沢',
            walkingMinutes: 15
        },

        // ========== 埼玉県の主要高校 ==========
        {
            id: 124,
            name: "埼玉県立浦和高等学校",
            category: "highschool",
            lat: 35.8604,
            lng: 139.6433,
            description: "県立男子校の最難関。",
            icon: "🏫",
            address: "埼玉県さいたま市浦和区領家5-3-3",
            hours: "平日 8:30〜17:00",
            phone: "048-886-3000",
            website: "https://urawa-h.spec.ed.jp/",
            lines: ['keihinTohoku'],
            nearestStation: '北浦和',
            walkingMinutes: 10
        },
        {
            id: 125,
            name: "埼玉県立浦和第一女子高等学校",
            category: "highschool",
            lat: 35.8618,
            lng: 139.6467,
            description: "県立女子校の最難関。",
            icon: "🏫",
            address: "埼玉県さいたま市浦和区岸町3-8-45",
            hours: "平日 8:30〜17:00",
            phone: "048-829-2031",
            website: "https://urawa-ichijo-h.spec.ed.jp/",
            lines: ['keihinTohoku'],
            nearestStation: '北浦和',
            walkingMinutes: 12
        }
    ]
};

// カテゴリ設定
const categoryConfig = {
    station: {
        name: "駅・交通",
        color: "#E53935",
        icon: "🚉"
    },
    shopping: {
        name: "ショッピング",
        color: "#FB8C00",
        icon: "🛍️"
    },
    education: {
        name: "大学",
        color: "#43A047",
        icon: "🎓"
    },
    highschool: {
        name: "高等学校",
        color: "#66BB6A",
        icon: "🏫"
    },
    medical: {
        name: "医療機関",
        color: "#1E88E5",
        icon: "🏥"
    },
    public: {
        name: "公共施設",
        color: "#8E24AA",
        icon: "🏛️"
    },
    park: {
        name: "公園",
        color: "#00897B",
        icon: "🌳"
    },
    disaster: {
        name: "防災施設",
        color: "#D32F2F",
        icon: "🛡️"
    }
};
